export const pathnames = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  LOGIN_ADMIN: 'login',
  RESUME: '/resume',
  STUDENTS: 'students',
  COURSES: 'courses',
  PROGRAMS: 'programs',
  DEPARTMENTS: 'departments',
  ACADEMIC_STRUCTURE: 'academic-structure',
  ACADEMIC_PASS: 'academic-pass',
  FEE_STATUS: 'fee-status',
  ORGANIGRAM: 'organigram',
  FORM_B: 'form-b',
  ADMIN: 'admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADD_STUDENTS: 'students/add-student',
  ADD_COURSES: 'courses/add-courses',
  ADD_PROGRAMS: 'programs/add-programs',
  ADD_DEPARTMENTS: 'departments/add-departments',
  INSTITUTIONAL_DATA: 'institutional-data',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_TERMS_OF_USE: '/terms-of-use',
  UNAUTHORIZED: '/unauthorized',
};
